CREATE DATABASE SimpleToDoApp
GO

USE SimpleToDoApp

CREATE TABLE Users
(
	Id INT PRIMARY KEY IDENTITY,
	Username NVARCHAR(50) UNIQUE NOT NULL,
	[Password] NVARCHAR(50) NOT NULL,
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	IsAdmin BIT NOT NULL,
	CreationDate DATETIME2 NOT NULL,
	CreatorId INT FOREIGN KEY REFERENCES Users(Id) NOT NULL,
	LastChangeDate DATETIME2 NOT NULL,
	LastChangeUserId INT FOREIGN KEY REFERENCES Users(Id) NOT NULL
)

CREATE TABLE ToDoLists
(
	Id INT PRIMARY KEY IDENTITY,
	Title NVARCHAR(150) NOT NULL,
	CreationDate DATETIME2 NOT NULL,
	CreatorId INT FOREIGN KEY REFERENCES Users(Id) NOT NULL,
	LastChangeDate DATETIME2 NOT NULL,
	LastChangeUserId INT FOREIGN KEY REFERENCES Users(Id) NOT NULL
)

CREATE TABLE Tasks
(
	Id INT PRIMARY KEY IDENTITY,
	Title NVARCHAR(150) NOT NULL,
	[Description] NVARCHAR(MAX) NOT NULL,
	IsCompleted BIT NOT NULL,
	CreationDate DATETIME2 NOT NULL,
	CreatorId INT FOREIGN KEY REFERENCES Users(Id) NOT NULL,
	LastChangeDate DATETIME2 NOT NULL,
	LastChangeUserId INT FOREIGN KEY REFERENCES Users(Id) NOT NULL
)

CREATE TABLE UsersToDoLists
(
	UserId INT REFERENCES Users(Id) NOT NULL,
	ToDoListId INT REFERENCES ToDoLists(Id) NOT NULL,
	CONSTRAINT PK_UserTask PRIMARY KEY (UserId, ToDoListId)
)

CREATE TABLE UsersTasks
(
	UserId INT REFERENCES Users(Id) NOT NULL,
	TaskId INT REFERENCES Tasks(Id) NOT NULL,
	CONSTRAINT PK_UserToDoList PRIMARY KEY (UserId, TaskId)
)